const constants = {
    QUERY_GO: 'QUERY_GO',
    UPDATE_USER_CRED: 'UPDATE_USER_CRED',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'
}

export { constants }